docs_dir: docs/book
site_dir: docs/html
nav:
  - Home: index.md
  - Introduction: intro.md
  - 'Quick Start': quick-start.md
  - Reference:
      - 'Dynamic Fields': dynamic-fields.md
      - Examples: examples.md
  - 'User Management':
      - Permissions: user-permissions.md
      - 'Form Tabs': user-formtabs.md
      - 'Form Fields': user-formfields.md
      - 'Index Columns': user-indexcols.md
site_name: oneplace-core
site_description: "onePlace Application Framework Core Module"
repo_url: 'https://github.com/OnePlc/PLC_X_Core'
theme:
  name: bootstrap4
extra:
  project: onePlc
